# Generated by `eventlog setup`. Keep the host Drovefile project-owned:
# load(".context/eventlog-reactors.star", "eventlog_reactors")
# and include eventlog_reactors() in an existing workspace's panes list.
def eventlog_reactors():
    committer = herdr.tab("composer-2.5-fast: commit reactor", panes = [
        pane("committer-reactor", serve = ["eventlog", "react", "--as", "committer", "--on", "result", "--timeout", "600s", "--git", "--", "eventlog", "action", "commit"], ready = output("watching")),
    ])
    docs = herdr.tab("claude-sonnet: docs reactor", panes = [
        pane("docs-reactor", serve = ["eventlog", "react", "--as", "doc-worker", "--on", "ack", "--filter", "by=committer", "--filter", "outcome=committed", "--timeout", "600s", "--", "eventlog", "action", "docs"], ready = output("watching"), after = ["committer-reactor"]),
    ])
    return [committer, docs]
